version: '3.1'

networks:
  devnet:
    external:
      name: devnet

services:
  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "false"   # deactivate HTTPS
    ports:
      #- "6443:443"
      - "8081:80"
    networks:
      - devnet