version: "3.7"
services:     
  dds_liferay:
    #image: liferay/dxp:7.4.13-u30
    #image: liferay/dxp:7.4.13-u56
    image: liferay/dxp:7.4.13-u46
    #image: liferay/dxp:7.4.13-u92
    container_name: dds_liferay
    environment:
      LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_DELAY: 10
      LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_MAX_PERIOD_RETRIES: 10
      LIFERAY_JVM_OPTS: "-Xms2560m -Xmx4096m"
      LCP_SECRET_DATABASE_NAME: liferay742
      #SYSTEM_LIFERAY_HTTP_PERIOD_PROXY_UPPERCASEH_OST: monproxyhost
      #LIFERAY_JPDA_ENABLED: "true" # debug
      #LIFERAY_SETUP_PERIOD_WIZARD_PERIOD_ENABLED: "true"
      #LIFERAY_SETUP_PERIOD_WIZARD_PERIOD_ADD_PERIOD_SAMPLE_PERIOD_DATA: "true"
      #LIFERAY_DEFAULT_PERIOD_ADMIN_PERIOD_FIRST_PERIOD_NAME: "Superadmin"
      #LIFERAY_DEFAULT_PERIOD_ADMIN_PERIOD_EMAIL_PERIOD_ADDRESS_PERIOD_PREFIX: "superadmin"
      #LIFERAY_DEFAULT_PERIOD_ADMIN_PERIOD_SCREEN_PERIOD_NAME: "superadmin"
      #LIFERAY_DEFAULT_PERIOD_ADMIN_PERIOD_PASSWORD: "test"
    networks: 
      - devnet
    ports: 
      - 18080:8080
      - 127.0.0.1:11311:11311
      - 15005:5005 # debug
    volumes:
      - ./mount:/mnt/liferay
      - liferay-data:/opt/liferay/data
      - liferay-osgi-configs:/opt/liferay/osgi/configs
      #- liferay-osgi-marketplace:/opt/liferay/osgi/marketplace
      #- liferay-osgi-modules:/opt/liferay/osgi/modules
      - liferay-osgi-war:/opt/liferay/osgi/war
      - ./liferay/deploy:/opt/liferay/deploy
      - ./liferay/osgi/modules:/opt/liferay/osgi/modules


networks:
  devnet:
    external:
      name: devnet


volumes:
  liferay-data:
  liferay-osgi-configs:
  #liferay-osgi-marketplace:
  #liferay-osgi-modules:
  liferay-osgi-war:
