version: "3.7"
services:     
  dds_liferay:
    image: liferay/dxp:7.4.13-u20
    container_name: dds_liferay
    environment:
      LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_DELAY: 10
      LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_MAX_PERIOD_RETRIES: 10
      LIFERAY_JVM_OPTS: "-Xms2560m -Xmx4096m"
    networks: 
      - devnet
    ports: 
      - 8080:8080
      - 127.0.0.1:11311:11311
    volumes:
      - ./mount:/mnt/liferay
      - liferay-data:/opt/liferay/data
      - liferay-osgi-configs:/opt/liferay/osgi/configs
      #- liferay-osgi-marketplace:/opt/liferay/osgi/marketplace
      #- liferay-osgi-modules:/opt/liferay/osgi/modules
      - liferay-osgi-war:/opt/liferay/osgi/war
      - ./liferay/deploy:/opt/liferay/deploy
      - ./liferay/osgi/modules:/opt/liferay/osgi/modules

networks:
  devnet:
    external:
      name: devnet


volumes:
  liferay-data:
  liferay-osgi-configs:
  #liferay-osgi-marketplace:
  #liferay-osgi-modules:
  liferay-osgi-war:
