version: "3"
services:
  liferay:
    container_name: dds-liferay-full
    hostname: dds-liferay-full  
    build:
      dockerfile: liferay/Dockerfile
      context: .
      args:
        - BASE_IMAGE=liferay/portal:7.4.3.132-ga132
      #  - BASE_IMAGE=liferay/dxp:2025.q3.3
    ports:
      - "80:8080"
    env_file:
      - ./liferay/variables.env
    volumes:
      - liferay_data:/opt/liferay/data
      - ./liferay/files:/mnt/liferay/files
      - ./liferay/deploy:/opt/liferay/deploy
    depends_on:
      - db
    entrypoint: /usr/local/bin/wait-for -t 60 db:3306 -- /usr/local/bin/liferay_entrypoint.sh
  db:
    image: mysql:8
    env_file:
      - ./mysql/variables.env
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    cap_add:
      - SYS_NICE
volumes:
  liferay_data:
  db_data:
