version: '2'
services:
    app-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/user1/app-postgresql/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=dbapp
            - POSTGRES_USER=dbuser
            - POSTGRES_PASSWORD=dbpassword
        ports:
            - 5432:5432

