version: '3.3'
name: "dds"

services:
  drupal:
    build: 
      context: .
      dockerfile: drupal.Dockerfile
    container_name: dds-drupal
    hostname: dds-drupal
    ports:
      - 9980:8080
    environment:
      - DRUPAL_DATABASE_HOST=dds-drupal-mariadb
      - DRUPAL_DATABASE_PORT_NUMBER=3306
      - DRUPAL_DATABASE_USER=bn_drupal
      - DRUPAL_DATABASE_NAME=bitnami_drupal
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - DRUPAL_SITE_NAME=MonSiteDrupal
      - DRUPAL_USERNAME=admin
      - DRUPAL_PASSWORD=admin
      - DRUPAL_EMAIL=admin@monsite.com

    volumes:
      - 'drupal_data:/bitnami/drupal'
    networks:
      - devnet      
    depends_on:
      - mariadb

  mariadb:
    build: 
      context: .
      dockerfile: mariadb.Dockerfile
    container_name: dds-drupal-mariadb
    hostname: dds-drupal-mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_drupal
      - MARIADB_DATABASE=bitnami_drupal
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    networks:
      - devnet      



volumes:
  mariadb_data:
    driver: local
  drupal_data:
    driver: local

networks:
  devnet:
    external:
      name: devnet