version: "3"

services:
  dds-traefik:
    container_name: dds-traefik
    build:
      context: .    
      dockerfile: traefik.Dockerfile    
    networks:
      - devnet
    ports:
      - "80:80"
    #  - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./config/traefik.toml:/etc/traefik/traefik.toml
    #  - ./config/acme.json:/acme.json
      - dds-traefik-acme:/acme/acme.json 
    #restart: unless-stopped
    # command:
    #   #- "--log.level=DEBUG"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.local`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"

volumes:
  dds-traefik-acme:

networks:
  devnet:
    external:
      name: devnet      