version: "3"

services:
  dds-traefik:
    #image: traefik:1.7.19
    image: traefik:2.10.7
    container_name: dds-traefik
    networks:
      - devnet
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.toml:/traefik.toml"
    #restart: unless-stopped
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
    labels:
      #- "traefik.frontend.rule=Host:traefik.local"
      - "traefik.port=8080"
      #- "traefik.backend=traefik"
      #- "traefik.frontend.entryPoints=http"
      - "traefik.http.routers.whoami.rule=Host(`traefik.local`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  dds-traefik-demo:
    image: tutum/hello-world
    container_name: dds-traefik-demo
    networks:
      - devnet
    ports:
      - "26000:80"
    labels:
      #- "traefik.enable=true"
      #- "traefik.frontend.rule=Host:hello-world.local"
      #- "traefik.backend=hello-world"
      - "traefik.port:26000"
      #- "traefik.frontend.entryPoints=http"
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`hello-world.local`)"
      - "traefik.http.routers.whoami.entrypoints=web"



networks:
  devnet:
    external:
      name: devnet      