defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  
[web]
address = ":8080"

[web.auth.basic]
  users = ["admin:$apr1$o1HmXW0i$wWgVewL1kLu9gaqmMDh6u/"]
  
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "test"
watch = true
exposedbydefault = true
