services:
    dnsmasq:
        image: 'jpillora/dnsmasq:latest'
        container_name: dnsmasq
        ports:
            - '127.0.0.2:53:53/udp'
            - '127.0.0.2:53:53/tcp'
            - '5353:53/udp'
            - '5353:53/tcp'
            - '8053:8080'
        volumes:
            - './dnsmasq.conf:/etc/dnsmasq.conf'
        cap_add:
            - NET_ADMIN
        environment:
            - HTTP_USER=admin
            - HTTP_PASS=admin
        #restart: unless-stopped
