# Configuration dnsmasq

# Ne pas utiliser /etc/resolv.conf du conteneur
no-resolv

# Serveurs DNS upstream (pour les domaines non locaux)
server=8.8.8.8
server=8.8.4.4

# Entrées DNS locales
address=/myoidc.local/127.0.0.1
address=/dev1.local/127.0.0.1

# Log des requêtes DNS (utile pour le debug)
log-queries
log-facility=-
