version: '3'

networks:
  devnet:
    external:
      name: devnet

services: 
  oracle-db:
    image: konnecteam/docker-oracle-12c:sequelize
    container_name: 'oracle12cR1'
    volumes: 
      - ./data:/u01/app/oracle
    ports: 
      - 1521:1521
      - 8080:8080
    networks:
       - devnet
  
