version: '3'

networks:
  devnet:
    external:
      name: devnet

services: 
  mongo-db:
    image: konnecteam/docker-oracle-12c:sequelize
    container_name: 'oracle12cR1'
    environment: 
      - MONGO_INITDB_DATABASE=mongodb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes: 
      - ./data:/u01/app/oracle
    ports: 
      - 1521:1521
    networks:
       - devnet
  