version: "3"

name: "dds"

networks:
  devnet:
    external:
      name: devnet


services:
  elasticsearch:
    build: 
      context: .
      dockerfile: elasticsearch.Dockerfile  
    container_name: dds-elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=LiferayElasticsearchCluster
      - xpack.security.enabled=false
      - network.bind_host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
       - "9200:9200"
       - "9300:9300"
    networks:
       - devnet
    depends_on:
      - fixsysctl
      
  fixsysctl:
    restart: "no"
    privileged: true
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 25m
    image: centos:7
    command: "sysctl -w vm.max_map_count=262144"       