version: "3"

networks:
  devnet:
    external:
      name: devnet

services:
  elasticsearch:
    build: .
    environment:
      - discovery.type=single-node
      - cluster.name=LiferayElasticsearchCluster
      - xpack.security.enabled=false
      - network.bind_host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
       - "9200:9200"
       - "9300:9300"
    networks:
       - devnet