#FROM sonarqube:7.9.2-community
#FROM sonarqube:7.9.1-community
FROM sonarqube:9.8.0-community
#FROM sonarqube

LABEL maintainer="Thierry Touin  <thierrytouin.pro@gmail.com>"

# INSTALL UTILITIES
USER root
#RUN ["apt-get", "clean"]
#RUN ["apt-get", "update"]
#RUN ["apt-get", "-y", "install", "wget"]

# Plugin installation

# Checkstyle
RUN ["wget", "-P", "/opt/sonarqube/extensions/plugins/","https://github.com/checkstyle/sonar-checkstyle/releases/download/4.29/checkstyle-sonar-plugin-4.29.jar"]

# Code Smells
RUN ["wget", "-P", "/opt/sonarqube/extensions/plugins/","https://github.com/QualInsight/qualinsight-plugins-sonarqube-smell/releases/download/qualinsight-plugins-sonarqube-smell-4.0.0/qualinsight-sonarqube-smell-plugin-4.0.0.jar"]

# PMD
RUN ["wget", "-P", "/opt/sonarqube/extensions/plugins/","https://github.com/jensgerdes/sonar-pmd/releases/download/3.2.1/sonar-pmd-plugin-3.2.1.jar"]

# FindBugs
#RUN ["wget", "-P", "/opt/sonarqube/extensions/plugins/","https://github.com/spotbugs/sonar-findbugs/releases/download/3.11.1/sonar-findbugs-plugin-3.11.1.jar"]
#RUN ["wget", "-P", "/opt/sonarqube/extensions/plugins/","https://github.com/spotbugs/sonar-findbugs/releases/download/3.9.4/sonar-findbugs-plugin-3.9.4.jar"]
#RUN ["wget", "-P", "/opt/sonarqube/extensions/plugins/","https://github.com/spotbugs/sonar-findbugs/releases/download/3.11.0/sonar-findbugs-plugin-3.11.0.jar"]

# sonar-js
# RUN ["wget", "-P", "/opt/sonarqube/extensions/plugins/","https://sonarsource.bintray.com/Distribution/sonar-javascript-plugin/sonar-javascript-plugin-4.2.1.6529.jar"]

# sonar-css
#RUN ["wget", "-P", "/opt/sonarqube/extensions/plugins/","https://binaries.sonarsource.com/Distribution/sonar-css-plugin/sonar-css-plugin-1.4.2.2002.jar"]

# sonar-java
#RUN ["wget", "-P", "/opt/sonarqube/extensions/plugins/","https://binaries.sonarsource.com/Distribution/sonar-java-plugin/sonar-java-plugin-7.9.0.28969.jar"]

# sonar-ts
# RUN ["wget", "-P", "/opt/sonarqube/extensions/plugins/","https://sonarsource.bintray.com/Distribution/sonar-typescript-plugin/sonar-typescript-plugin-1.7.0.2893.jar"]

RUN ["chown", "-R", "sonarqube:sonarqube", "/opt/sonarqube/extensions/plugins/"]
#RUN ["chown", "-R", "sonarqube:sonarqube", "/opt/sonarqube/extensions/downloads/"]

USER sonarqube
