version: '3.4'

networks:
  devnet:
    external:
      name: devnet

services:
    sonarqube:
        image: sonarqube
        environment:
            - sonar.jdbc.url=jdbc:postgresql://sonarqube-postgresql:5432/sonar
        volumes:
            - sonarqube_conf:/opt/sonarqube/conf
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions
        ports:
            - 19000:9000
            - 19092:9092
        networks:
            - devnet

    sonarqube-postgresql:
        image: postgres:10.4
        environment:
           - POSTGRES_USER=sonar
           - POSTGRES_PASSWORD=sonar
        volumes:
           - postgresql:/var/lib/postgresql
        # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
           - postgresql_data:/var/lib/postgresql/data
        ports:
            - 15432:5432
        networks:
            - devnet


volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  postgresql_data: