version: '3.4'

networks:
  devnet:
    external:
      name: devnet

services:
    sonarqube:
        build: 
            context: .
            dockerfile: Dockerfile.sonarserver
        command: -Dsonar.ce.javaOpts=-Xmx4096m -Dsonar.web.javaOpts=-Xmx4096m -Dsonar.search.javaAdditionalOpts=-Dnode.store.allow_mmapfs=false  
        environment:
            - sonar.jdbc.url=jdbc:postgresql://sonarqube-postgresql:5432/sonar
        volumes:
            - sonarqube_conf:/opt/sonarqube/conf
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions_plugins:/opt/sonarqube/extensions/plugins
            - sonarqube_extensions_downloads:/opt/sonarqube/extensions/downloads
            - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
        ports:
            - 19000:9000
            - 19092:9092
        networks:
            - devnet
        depends_on:
            - sonarqube-postgresql

    sonarqube-postgresql:
        image: postgres:10.4
        environment:
           - POSTGRES_USER=sonar
           - POSTGRES_PASSWORD=sonar
        volumes:
           - sonarqube_postgresql:/var/lib/postgresql
        # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
           - sonarqube_postgresql_data:/var/lib/postgresql/data
        ports:
            - 15432:5432
        networks:
            - devnet


volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions_plugins:
  sonarqube_extensions_downloads:
  sonarqube_bundled-plugins:  
  sonarqube_postgresql:
  sonarqube_postgresql_data: