# Correspondances DNS locales
# Format : hostname=adresse_ip
# Ces entrées seront résolues directement par l'agent Java
# sans nécessiter de serveur DNS externe.

myoidc.local=127.0.0.1
dev1.local=127.0.0.1
