version: '3.4'
services:
    sonarqube:
        image: sonarqube
        environment:
            - POSTGRES_DB=dbapp
            - POSTGRES_USER=dbuser
            - POSTGRES_PASSWORD=dbpassword
        ports:
            - 9000:9000
            - 9092:9092



