version: '3.4'

networks:
  devnet:
    external:
      name: devnet

services:
    sonarqube:
        image: sonarqube
        environment:
            - POSTGRES_DB=dbapp
            - POSTGRES_USER=dbuser
            - POSTGRES_PASSWORD=dbpassword
        ports:
            - 19000:9000
            - 19092:9092
        networks:
            - devnet


