version: '3.4'

networks:
  devnet:
    external:
      name: devnet

services:
    sonar-cli:
        build: 
            context: .
            dockerfile: Dockerfile.sonarscanner-3.0.3-alpine
        volumes:
            - ${sources_directory}:/usr/src
        environment:
            - TZ=Europe/Paris
        networks:
            - devnet


