version: "3"

networks:
  devnet:
    external:
      name: devnet

services:
  apache:
    image: httpd:2.4
    ports:  
       - "80:80"
       - "443:443"
       - "643:443"
    volumes:
       - ./config:/usr/local/apache2/conf
    networks:
       - devnet