version: '2'

services:
    dds_fm:
        image: serverwentdown/file-manager
        container_name: dds_fm
        ports:
            - "9980:8080"        
        volumes:
            - ./data:/data

