version: '3.3'

name: "dds"

networks:
  devnet:
    external:
      name: devnet

services:
    postgresql:
        image: postgres:13.5
        container_name: dds-postgresql
        volumes:
            - postgresql_data:/var/lib/postgresql/data
            - ./config:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_USER=dbuser
            - POSTGRES_PASSWORD=dbpassword
        ports:
            - 5432:5432
        networks:
            - devnet
            
volumes:
  postgresql_data:

