version: '3.3'


networks:
  devnet:
    external:
      name: devnet

services:
    dds_postgresql:
        image: postgres:13.5
        container_name: dds_postgresql
        volumes:
            - database_data:/var/lib/postgresql/data
            #- ./database-data:/var/lib/postgresql/data
            #- ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./config:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_USER=dbuser
            - POSTGRES_PASSWORD=dbpassword
        ports:
            - 5432:5432
        networks:
            - devnet
            
volumes:
  database_data:

