version: '3'

services:
  ecmd-ui:
    container_name: ecmd-ui
    build: 
        context: .
        dockerfile: ecmd-ui.Dockerfile
        args: 
          - TITLE=${TITLE} 
          - TOOLS_LINK=${TOOLS_LINK}
          - DDS_LINK=${DDS_LINK}
          - OTHER1_LINK=${OTHER1_LINK}

    ports:
      - "7777:80"


