version: "3"

networks:
  devnet:
    external:
      name: devnet

services:
  omnidb:
    #build: .
    image: taivokasper/omnidb
    container_name: dds_omnidb
    ports:
      #- "8000:8000"
      - "8000:8080"
      - "25482:25482"
    networks:
       - devnet