spring:
  application:
    name: dns-check
  main:
    banner-mode: off

# Domaines à vérifier (séparés par des virgules)
dns:
  check:
    domains: myoidc.local,dev1.local

logging:
  level:
    root: WARN
    com.example.dnscheck: INFO
