#version: '3.4'
version: '2.4'

networks:
  devnet:
    external:
      name: devnet

volumes:
  bashhistory:

services:
    dev-app:
        build: .
        environment:
            - TZ=Europe/Paris
            - JAVA_OPTIONS=-Xmx2048m -Xms256m
            - SPRING_PROFILES_ACTIVE=dev,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://app-postgresql:5432/dbapp
            - SPRING_DATASOURCE_USERNAME=dbuser
            - SPRING_DATASOURCE_PASSWORD=dbpassword
            - APPLICATION_SLEEP=10 # gives time for the database to boot before the application
            - HISTFILE=/home/user1/hist/.bash_history   
        volumes:
            - ${sources_directory}:/home/user1/app
            - ~/.m2:/home/user1/.m2
            #- ~/.posteDeDev/.bash_history:/home/user1/.bash_history
            - bashhistory:/home/user1/hist
        ports:
            - 8080:8080
            - 9090:9090
            - 5005:5005
        cpu_shares: 200 
        mem_limit: 4096M
        networks:
            - devnet


    app-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/user1/app-postgresql/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=dbapp
            - POSTGRES_USER=dbuser
            - POSTGRES_PASSWORD=dbpassword
        ports:
            - 5432:5432
        networks:
            - devnet
