version: '3.4'


networks:
  devnet:
    external:
      name: devnet

services:
    dev-app:
        build: .
        environment:
            - JAVA_OPTIONS=-Xmx2048m -Xms256m
            - SPRING_PROFILES_ACTIVE=dev,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://app-postgresql:5432/liferay71
            - SPRING_DATASOURCE_USERNAME=dbuser
            - SPRING_DATASOURCE_PASSWORD=dbpassword
            - APPLICATION_SLEEP=10 # gives time for the database to boot before the application
        volumes:
            - ${sources_directory}:/home/user1/app        
            - ~/.m2:/home/user1/.m2
            - ~/.posteDeDev/.bash_history:/home/user1/.bash_history
            - ./binaries:/home/user1/binaries
        ports:
            - 8080:8080
            #- 9200:9200 # Elasticsearch embeded
            #- 9300:9300 # Elasticsearch if remote
            - 5005:5005 # Debug port
        networks:
            - devnet

    app-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/user1/app-postgresql/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=liferay
            - POSTGRES_USER=dbuser
            - POSTGRES_PASSWORD=dbpassword
        ports:
            - 5432:5432
        networks:
            - devnet
            
    elasticsearch:
        image: elasticsearch:6.8.3
        environment:
          - discovery.type=single-node
          - cluster.name=LiferayElasticsearchCluster
          - xpack.security.enabled=false
          - network.bind_host=0.0.0.0
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - devnet
