version: '3.4'

networks:
  devnet:
    external:
      name: devnet

services:
    sonar-cli:
        build: 
            context: .
            dockerfile: ./Dockerfile.sonarclient
        volumes:
            - ${sources_directory}:/usr/src
            - ./config/sonar-scanner.properties:/usr/lib/sonar-scanner/conf/sonar-scanner.properties
        environment:
            - TZ=Europe/Paris
        networks:
            - devnet


