version: "3"

networks:
  devnet:
    external:
      name: devnet

services:
  dds_kong:
    image: kong/kong-gateway:3.6.0.0
    container_name: dds_kong
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
    ports: 
      - 8000:8000
      - 8001:8001  
      - 8002:8002  
      - 8003:8003  
      - 8004:8004
      - 8443:8443
      - 8444:8444
      - 8445:8445  
    volumes:
      - ./kong/declarative:/kong/declarative/
    networks:
       - devnet
