version: "3"

networks:
  devnet:
    external:
      name: devnet

services:
  #VSCode
  dds_vscode:
    container_name: dds_vscode
    build: 
        context: .
        dockerfile: code-server.Dockerfile
    volumes:
      - ./config:/home/coder/.config
      - ./data:/home/coder/project

    #volumes:
      # Set <project dir> to the directory you want to open in VS Code.
      #- ./data:/project
      # <vs code config> should point to a local dir where vs code stores its data.
      #- ./data/vscode:/home/coder/.local/share/code-server
    ports:
      - "13219:8080"
    command: code-server --auth none --disable-telemetry 
    #command: /bin/bash -c "/home/coder/init.sh && code-server --auth password"
    # command: >
    #   sh -c "
    #     /home/coder/init.sh &&
    #     code-server --auth password
    #   "  

    #restart: unless-stopped
    networks:
       - devnet


