version: "3"

networks:
  devnet:
    external:
      name: devnet

services:
  #VSCode
  dds_vscode:
    container_name: dds_vscode
    build: 
        context: .
        dockerfile: code-server.Dockerfile
    environment:
      - PUID=1000                # À adapter selon votre utilisateur hôte
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./custom/local:/home/coder/custom-local:ro
      - ./custom/scripts:/home/coder/custom-scripts:ro
      - ./custom/config/code-server/config.yaml:/home/coder/.config/code-server/config.yaml
      - ./data:/home/coder/project
      - ../../../../docker-dev-station:/home/coder/docker-dev-station
    ports:
      - "13219:8080"
    command: code-server --auth none --disable-telemetry /home/coder
    #restart: unless-stopped
    networks:
       - devnet


