version: '3.3'


networks:
  devnet:
    external:
      name: devnet

services:
    dds_mysql:
      image: "mysql:5.7"
      container_name: dds_mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=ddslportal
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=dbpassword
      command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --character-set-filesystem=utf8
      ports:
        - "3306:3306"
      networks:
        - devnet
      volumes:
        - type: volume
          source: dds-mysql-data
          target: /var/lib/mysql
        - type: bind
          source: ./mysql/database
          target: /docker-entrypoint-initdb.d
        - ./mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf

            
volumes:
  dds-mysql-data:

